security.jwt.token.secret-key: my-secret-key

spring:
  application:
    name: planner
  datasource:
    url: jdbc:mysql://localhost:3306/planner-db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
